### ISSUE TITLE
ready for commercial use?

### ISSUE THREAD

**Issue by giannik** [i-bank/api-demo#1]
Hello.
I am working for a greek company interested in integrating payments through nbg-api.
Is nbg api ready for commercial usage. ?
What is the road map or procedure to use for professional use?
Thank you in advance
Yiannis Kyriazidis.

**Comment by faniskou** [comment]
Sorry for the delayed answer.
We have more than 3 apis that are exposed on internet for commercial use.   We are sure that after we talk about what you want to do we can guide you through . Please contact us  on kouvaris.th@nbg.gr biks@nbg.gr
